package com.taytelar.util;

public class Constants {
    private Constants() {

    }
    public static final int RETURN_DAYS_POLICY = 7;
    public static final String NORMAL_AUTHENTICATION = "Normal Registration";
    public static final String GOOGLE_AUTHENTICATION = "Google Registration";
    public static final String FACEBOOK_AUTHENTICATION = "Facebook Registration";
    public static final String APPLE_AUTHENTICATION = "Apple iOS Registration";
    public static final String GOOGLE = "google";
    public static final String FACEBOOK = "facebook";
    public static final String APPLE = "apple";
    public static final String LOGIN = "login";
    public static final String REGISTER = "Register";
    public static final String CUSTOMER = "customer";
    public static final String AFFILIATE = "affiliate";
    public static final String SUCCESS = "Success";
    public static final String ERROR = "Error";
    public static final String AFFILIATE_USER_ID = "AID";
    public static final String PAYMENT_ID = "PAY";
    public static final String CART_ITEM_ID = "CT-ID";
    public static final String ORDER_ID = "TT";
    public static final String ORDER_ITEM_ID = "IT";
    public static final String CART_ID = "CID";
    public static final String USER_ID = "UID";
    public static final String USER_NOT_FOUND = "User Not Found";
    public static final String COD = "Cash On Delivery";
    public static final String ORDER_PLACED_SUCCESSFULLY = "Order Placed Successfully";
    public static final String ORDER_NOT_FOUND = "Order not found for the given orderId";
    public static final String PAYMENT_SUCCESS = "Payment successful";
    public static final String PAYMENT_FAILED = "Payment failed";
    public static final String PAYMENT_CREATED_SUCCESSFULLY = "Payment created successfully";
    public static final String ERROR_MESSAGE = "Error creating Razorpay order: ";
    public static final String REGISTER_SUCCESS = "Registration Successful";
    public static final String USER_DETAILS_MISS_MATCH = "The provided phone number does not match with the provided phone number for otp or ";
    public static final String ADDED_TO_CART_SUCCESSFULLY = "Added to Cart Successfully";
    public static final String CART_ITEM_UPDATE = "Cart Item Updated Successfully";
    public static final String CART_NOT_FOUND = "Cart not found for user";
    public static final String CART_ITEM_DELETED = "Cart Item Deleted Successfully";
    public static final String OTP_VERIFIED_SUCCESSFULLY = "Otp verified successfully";
    public static final String OTP_VERIFIED_FAILED = "Otp verified failed";
    public static final String INVALID_REFERRAL_CODE = "The provided referral code is InvalidReferralCode";
    public static final String OTP_FAILED = "Failed to send OTP";
    public static final String OTP_SUCCESS = "OTP sent successfully";
    public static final String USER_ALREADY_EXIST = "Customer already exists with the provided phone number";
    public static final String AFFILIATE_USER_ALREADY_EXIST = "Affiliate user already exists with the provided phone number";
    public static final String OTP_ENTITY_NOT_FOUND = "OTPEntity not found with the provided phone number";
    public static final String OTP_NOT_VERIFIED = "OTP not verified with the provided phone number";
    public static final String UNKNOWN_USER_TYPE = "The provided user type from request is invalid";
    public static final String USER_ACCOUNT_NOT_EXIST = "Customer account not exist";
    public static final String AFFILIATE_USER_ACCOUNT_NOT_EXIST = "Affiliate user account not exist";
    public static final String ADDRESS_ALREADY_EXIST = "Address already exists";
    public static final String ADDRESS_ADDED_SUCCESSFULLY = "Address added successfully";
    public static final String ADDRESS_UPDATED_SUCCESSFULLY = "Address updated successfully";
    public static final String ADDRESS_NOT_FOUND = "Address not found";
    public static final String ADDRESS_DELETED_SUCCESSFULLY = "Address deleted successfully";
    public static final String CATEGORY_ID = "C";
    public static final String SUB_CATEGORY_ID = "SC";
    public static final String PRODUCT_ID = "PID";
    public static final String PRODUCT_ADDED_SUCCESSFULLY = "Product added successfully";
    public static final String ADMIN = "admin";
    public static final String ADMIN_ID = "AD-ID";
    public static final String BRACKETS = " : {}";
    public static final String ADMIN_USER_ACCOUNT_NOT_EXIST = "Admin user account not exist";
    public static final String UPLOAD_ERROR = "Failed to upload file to S3";
    public static final String ADMIN_USER_ALREADY_EXIST = "Admin user already exists";
    public static final String PRODUCT_NOT_FOUND = "Product not found";
    public static final String IMAGES_AND_VIDEO_ADDED_SUCCESSFULLY = "Images and video added successfully";
    public static final String STOCK_ID = "S-ID";
    public static final String COLOR_QUANTITY_ID = "CQ-ID";
}
